import { useRef, useState } from "react";
import "../assets/css/bootstrap.min.css";

const DBMHindiBook = () => {
  const images = [
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0001.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0002.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0003.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0004.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0005.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0006.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0007.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0008.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0009.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0010.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0011.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0012.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0013.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0014.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0015.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0016.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0017.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0018.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0019.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0020.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0021.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0022.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0023.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0024.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0025.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0026.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0027.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0028.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0029.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0030.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0031.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0032.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0033.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0034.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0035.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0036.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0037.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0038.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0039.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0040.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0041.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0042.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0043.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0044.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0045.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0046.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0047.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0048.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0049.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0050.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0051.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0052.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0053.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0054.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0055.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0056.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0057.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0058.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0059.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0060.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0061.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0062.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0063.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0064.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0065.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0066.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0067.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0068.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0069.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0070.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0071.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0072.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0073.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0074.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0075.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0076.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0077.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0078.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0079.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0080.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0081.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0082.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0083.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0084.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0085.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0086.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0087.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0088.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0089.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0090.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0091.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0092.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0093.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0094.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0095.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0096.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0097.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0098.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0099.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0100.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0101.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0102.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0103.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0104.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0105.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0106.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0107.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0108.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0109.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0110.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0111.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0112.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0113.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0114.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0115.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0116.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0117.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0118.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0119.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0120.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0121.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0122.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0123.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0124.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0125.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0126.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0127.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0128.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0129.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0130.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0131.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0132.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0133.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0134.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0135.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0136.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0137.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0138.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0139.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0140.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0141.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0142.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0143.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0144.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0145.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0146.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0147.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0148.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0149.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0150.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0151.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0152.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0153.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0154.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0155.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0156.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0157.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0158.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0159.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0160.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0161.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0162.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0163.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0164.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0165.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0166.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0167.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0168.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0169.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0170.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0171.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0172.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0173.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0174.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0175.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0176.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0177.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0178.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0179.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0180.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0181.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0182.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0183.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0184.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0185.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0186.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0187.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0188.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0189.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0190.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0191.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0192.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0193.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0194.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0195.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0196.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0197.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0198.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0199.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0200.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0201.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0202.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0203.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0204.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0205.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0206.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0207.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0208.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0209.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0210.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0211.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0212.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0213.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0214.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0215.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0216.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0217.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0218.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0219.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0220.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0221.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0222.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0223.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0224.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0225.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0226.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0227.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0228.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0229.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0230.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0231.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0232.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0233.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0234.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0235.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0236.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0237.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0238.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0239.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0240.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0241.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0242.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0243.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0244.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0245.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0246.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0247.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0248.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0249.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0250.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0251.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0252.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0253.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0254.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0255.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0256.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0257.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0258.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0259.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0260.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0261.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0262.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0263.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0264.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0265.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0266.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0267.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0268.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0269.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0270.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0271.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0272.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0273.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0274.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0275.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0276.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0277.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0278.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0279.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0280.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0281.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0282.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0283.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0284.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0285.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0286.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0287.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0288.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0289.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0290.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0291.webp",
    "/images/dbm-hindi/diploma-in-business-management-hindi_page-0292.webp",
  ];
  const imageRefs = useRef([]);
  const [inputValue, setInputValue] = useState("1");

  const handleInputChange = (e) => {
    const value = e.target.value;

    if (value === "") {
      setInputValue("");
      return;
    }

    const page = parseInt(value, 10);
    if (!isNaN(page) && page >= 1 && page <= images.length) {
      setInputValue(value);

      imageRefs.current[page - 1]?.scrollIntoView({
        behavior: "smooth",
        block: "start",
        inline: "nearest",
      });
    }
  };

  return (
    <div className="bg-pdf-gray">
      <div className="pdf-container">
        <div className="pdf-toolbar">
          <div className="pdf-header ps-4">
            <h4 className="text-white text-md-start text-center">
              Diploma In Business Management - Hindi
            </h4>
          </div>
          <div>
            <input
              type="number"
              value={inputValue}
              onChange={handleInputChange}
            />
            <span className="mx-2">/</span>
            <span>{images.length}</span>
          </div>
        </div>
        <div className="pdf-container">
          {images.map((image, index) => (
            <img
              key={index}
              src={image}
              alt={`Page ${index + 1}`}
              ref={(el) => (imageRefs.current[index] = el)}
              className="page-image"
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default DBMHindiBook;
